// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-uT-vEQNfXzjVlC7pUFDtiRBYvWpPAU',
    appId: '1:907295345432:web:f704ecd33b575a18b3ec6d',
    messagingSenderId: '907295345432',
    projectId: 'inner-palette',
    authDomain: 'inner-palette.firebaseapp.com',
    storageBucket: 'inner-palette.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpiJKZ_Iolu7Yih9piGncc-VDC3sL2tCc',
    appId: '1:907295345432:android:213087c26d41a69cb3ec6d',
    messagingSenderId: '907295345432',
    projectId: 'inner-palette',
    storageBucket: 'inner-palette.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLWWC1prchAoFaD-mjh_lMSH3hqmGlUEw',
    appId: '1:907295345432:ios:e3605b15146942edb3ec6d',
    messagingSenderId: '907295345432',
    projectId: 'inner-palette',
    storageBucket: 'inner-palette.appspot.com',
    iosBundleId: 'com.example.innerpalette',
  );
}
